// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWlpOO6hazAOujS-5kQPzYMM2sOE_OGTs',
    appId: '1:186561596562:web:294f07c696e054661fea4b',
    messagingSenderId: '186561596562',
    projectId: 'mynotes-flutter-project-8afd8',
    authDomain: 'mynotes-flutter-project-8afd8.firebaseapp.com',
    storageBucket: 'mynotes-flutter-project-8afd8.appspot.com',
    measurementId: 'G-MVE2YYE034',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC06C9kjLoqfkrGVrNb2j5h_4hVVZWcRF4',
    appId: '1:186561596562:android:81e5da83fed68d1d1fea4b',
    messagingSenderId: '186561596562',
    projectId: 'mynotes-flutter-project-8afd8',
    storageBucket: 'mynotes-flutter-project-8afd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYLNVAu1ZBODYJc0s2YsujFm6Ll2dpuF0',
    appId: '1:186561596562:ios:0df64af9c832abe31fea4b',
    messagingSenderId: '186561596562',
    projectId: 'mynotes-flutter-project-8afd8',
    storageBucket: 'mynotes-flutter-project-8afd8.appspot.com',
    iosClientId: '186561596562-ka92amdv15dn9ve16ru2b2ff7g2me1hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYLNVAu1ZBODYJc0s2YsujFm6Ll2dpuF0',
    appId: '1:186561596562:ios:0df64af9c832abe31fea4b',
    messagingSenderId: '186561596562',
    projectId: 'mynotes-flutter-project-8afd8',
    storageBucket: 'mynotes-flutter-project-8afd8.appspot.com',
    iosClientId: '186561596562-ka92amdv15dn9ve16ru2b2ff7g2me1hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
